### DISCUSSION TITLE
How to handle workspace-based dependencies

### DISCUSSION THREAD

**Discussion by barsoosayque** [ipetkov/crane#166] [Q&A] [answered]
I'm using my fork of [bevy_rapier3d](https://github.com/barsoosayque/bevy_rapier) with a specific branch in our project. _Cargo.toml_ looks something like this:
```toml
# ...
[patch.crates-io]
bevy_rapier3d = { git = 'https://github.com/barsoosayque/bevy_rapier', branch = "debug_visible"  }

[dependencies]
bevy_rapier3d = { version = "0.18", features = ["debug-render", "simd-nightly", "parallel"] }
``` 

The problem is that `bevy_rapier3d` is a workspace member of `bevy_rapier` repository, and in it's _Cargo.toml_, it uses `path = "../src/lib.rs"`. However, crane (and to be honest, both naersk and buildRustPackage have the same problem) only downloads the `bevy_rapier3d` directory and not the whole repo, so it just can't find the sources:
```
   Compiling bevy_rapier3d v0.18.0 (https://github.com/barsoosayque/bevy_rapier?branch=debug_visible#0340f5ef)
error: couldn't read /build/cargo-vendor-dir/bevy_rapier3d-0.18.0/../src/lib.rs: No such file or directory (os error 2)

error: could not compile `bevy_rapier3d` due to previous error
warning: build failed, waiting for other jobs to finish...
```
What do I have to do to make crane clone the whole repository and not just the subdirectory of the specific workspace member ? (note: building with cargo works just fine, I use it in my devshell)
