### ISSUE TITLE
Some way to have `buildDepsOnly` preserve extra files

### ISSUE THREAD

**Issue by dpc** [ipetkov/crane#111]
We need to use some wrappers around `linker`/`ar` binaries in `.cargo/config.toml`:

```toml
[target.armv7-linux-androideabi]
linker = "./.cargo/ld.armv7-linux-androideabi"
ar = "./.cargo/ar.armv7-linux-androideabi"

[target.aarch64-linux-android]
linker = "./.cargo/ld.aarch64-linux-android"
ar = "./.cargo/ar.aarch64-linux-android"

[target.x86_64-linux-android]
linker = "./.cargo/ld.x86_64-linux-android"
ar = "./.cargo/ar.x86_64-linux-android"

[target.i686-linux-android]
linker = "./.cargo/ld.i686-linux-android"
ar = "./.cargo/ar.i686-linux-android"
```

These are some custom scripts that use env variables to fix some Android toolchain issues.

Unfortunately, I discovered that `mkDummySrc` is not friendly to these, and all of them are stripped from the building src, so building project dependencies fails.

Some escape hatch, and maybe by default preserving whole `./cargo/` directory would be nice.
