### ISSUE TITLE
'error: Cannot find Git revision' with a branch

### ISSUE THREAD

**Issue by bbigras** [ipetkov/crane#13]
Maybe related to `ref 'master'` not matching `test-override`.

```toml
[dependencies]
chrono = { git = "https://github.com/bryanburgers/chrono", branch = "test-override", features = ["test-override", "serde"] }
```

```
error: Cannot find Git revision 'ffe62991c757de0877a53ec0d5aa30d597b7f24a' in ref 'master' of repository 'https://github.com/bryanburgers/chrono'! Please make sure that the rev exists on the ref you've specified or add allRefs = true; to fetchGit.
(use '--show-trace' to show detailed location information)
```
