### ISSUE TITLE
Triggering `compile_error` for mutually exclusive features when using `crane`

### ISSUE THREAD

**Issue by paulyoung** [ipetkov/crane#187]
I have a library whose `Cargo.toml` contains this:

```toml
[features]
async-network-client = ["git-repository/async-network-client"]
blocking-network-client  = ["git-repository/blocking-network-client", "maybe-async/is_sync"]

[dependencies]
git-repository = { workspace = true }
```

The library is either blocking or asynchronous depending on the feature.

The workspace `Cargo.toml` looks a bit like this:

```toml
[workspace]
members = [
    "crates/my-lib",
    "crates/async-bin",
    "crates/blocking-bin",
]

[workspace.dependencies]
my-lib = { path = "crates/my-lib" }
git-repository = { git = "https://github.com/Byron/gitoxide", rev="be0bbf519c4a6687c305717ec0c12215a5836f58" }
```

The `Cargo.toml` for the async bin contains:

```toml
[dependencies]
my-lib = { workspace = true, features = ["async-network-client"] }
```

and the `Cargo.toml` for the blocking bin contains:

```toml
[dependencies]
my-lib = { workspace = true, features = ["blocking-network-client"] }
```

So, the point is that the blocking and async versions never meet, and this all works fine when using `cargo`.

However, using `craneLib.buildPackage` triggers this [`compile_error`](https://github.com/Byron/gitoxide/blob/94750e15831969059551af35d31c21009462084d/git-packetline/src/lib.rs#L103-L104):

```
cargo-package-deps>     Checking git-packetline v0.14.0 (https://github.com/Byron/gitoxide?rev=be0bbf519c4a6687c305717ec0c12215a5836f58#be0bbf51)
cargo-package-deps> error: Cannot set both 'blocking-io' and 'async-io' features as they are mutually exclusive
cargo-package-deps>    --> /nix/store/vh461qhw021qsqn0n5nk1ww5gsvf15fv-vendor-cargo-deps/970279c888c350b6ce9a80c607fb387106db89a08bbd314de7387baf71ebb5b5/git-packetline-0.14.0/src/lib.rs:104:1
cargo-package-deps>     |
cargo-package-deps> 104 | compile_error!("Cannot set both 'blocking-io' and 'async-io' features as they are mutually exclusive");
cargo-package-deps>     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cargo-package-deps>     Checking clap v4.0.29
cargo-package-deps>     Checking git-config-value v0.9.0 (https://github.com/Byron/gitoxide?rev=be0bbf519c4a6687c305717ec0c12215a5836f58#be0bbf51)
cargo-package-deps>     Checking git-actor v0.14.1 (https://github.com/Byron/gitoxide?rev=be0bbf519c4a6687c305717ec0c12215a5836f58#be0bbf51)
cargo-package-deps> error: could not compile `git-packetline` due to previous error
```

(`git-repository` re-exports `git-packetline`)

My `flake.nix` contains this, which is pretty standard for my projects that use workspaces:

```nix
{
  # content omitted
  
  src = ./.;

  cargoArtifacts = craneLib.buildDepsOnly {
    inherit src;
    nativeBuildInputs = [
      pkgs.cmake
    ];
  };

  async-bin = craneLib.buildPackage rec {
    pname = "async-bin";
    inherit cargoArtifacts src;
  };
  
  # content omitted
}
```

Notice that I'm only trying to build the async binary so far and I'm still encountering the error.

If I comment out the blocking binary from the `members` section of the workspace `Cargo.toml`, I don't get the error.

Is there a way to address this or work around it?

I tried the following but ran into `error: unable to find Cargo.lock at nix/store/...`

```nix
{
  # content omitted
  
  async-bin = craneLib.buildPackage rec {
    pname = "async-bin";
    src = ./crates/async-bin;
  };

  # content omitted
}
```

Adding `cargoLock = ./Cargo.lock;` results in:

```
error: failed to parse manifest at `/private/tmp/nix-build-git-remote-tcp-deps-0.1.0.drv-0/dummy-src/Cargo.toml`
Caused by:
 failed to find a workspace root
```

Thanks in advance.
