### ISSUE TITLE
[package.] Sections Getting Stripped From Cargo.toml

### ISSUE THREAD

**Issue by benwis** [ipetkov/crane#291]
Hello! I think this is another change with the -Z build-std functionality, but it's stripping the package. sections from my Cargo.toml now, and I need those.

```toml
[package.metadata.cargo-all-features]
denylist = ["axum", "tower", "tower-http", "tokio", "sqlx", "leptos_axum", "femark", "chrono", "argon2","rand", "rand_core"]
skip_feature_sets = [["csr", "ssr"], ["csr", "hydrate"], ["ssr", "hydrate"]]

[package.metadata.leptos]
# The name used by wasm-bindgen/cargo-leptos for the JS/WASM bundle. Defaults to the crate name
output-name = "benwis_leptos"
```

Running `nix build . --keep-failed` shows every other tag in the file except these two. The first one isn't custom, and probably should stay, the second is.
