### ISSUE TITLE
Crane concatenates, not overwrites dependency sources overriden with `[patch]`

### ISSUE THREAD

**Issue by dpc** [ipetkov/crane#307]
I have a Rust project that uses crane to build where I have to include a dependency that is currently a private github repo. We're temporarily using a github access token to access it.

Relevant `Cargo.toml` sections looks somewhat like this:

```toml
[dependencies]
xyz = { git = "https://github.com/us/xyz/" }

[patch.'https://github.com/us/xyz/']
xyz = { git = "https://x-access-token:github_pat_...@github.com/us/xyz/", rev="..." }
```

The original `https://github.com/us/xyz/` was never meant to be fetched, and requires overriding in the current project and in any downstream one, until it's public.

This works perfectly when built from a nix develop shell, but in CI it builds but prints scary messages:

```
remote: Repository not found.
fatal: repository 'https://github.com/us/xyz/' not found
warning: could not read HEAD ref from repo at '***github.com/us/xyz', using 'master'
fatal: Refusing to point HEAD outside of refs/
warning: could not update cached head 'master' for '***github.com/us/xyz'
```

Again - the build itself seems to be completely fine... because crane seems to ignore that failure(?) and it's not actually used later. So it's not a big problem for us, but just wanted to report and document.

It would be neat-o if crane could just notice that `xyz`'s source has been completely overriden, and skip sourcing it, or if there was a way to explain to `crane` (maybe via a custom `Cargo.toml` section) to skip fetching some stuff.
