### ISSUE TITLE
Private git repositories can't be built

### ISSUE THREAD

**Issue by TheNeikos** [ipetkov/crane#332]
I have the following setup:

Cargo.toml
```toml
[package]
name = "private_package"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
foobar = { git = "ssh://git@gitlab.example.com:8080/foobar.git", branch = "main" }
```

flake.nix
```nix
     commonArgs = {
        src = ./.;
      };
      cargoArtifacts = craneLib.buildDepsOnly commonArgs;
      private_package = craneLib.buildPackage (commonArgs // {
        inherit cargoArtifacts;
      });
```

When I now run `cargo check` with the env variable `CARGO_NET_GIT_FETCH_WITH_CLI=true` it works fine and builds.

Now, when I run `nix build .#private_package` I get the following error when building `private_package-deps`

```
cargoArtifacts not set, will not reuse any cargo artifacts
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/kz72vid5f4jrkigw6ymzf7n6a11ygpjb-private_package
source root is private_package
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
Executing configureCargoCommonVars
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
will append /build/private_package/.cargo-home/config.toml with contents of /nix/store/qhzml8kifsmdrwk078ldpwqcivgdnjhw-vendor-cargo-deps/config.toml
default configurePhase, nothing to do
@nix { "action": "setPhase", "phase": "buildPhase" }
building
++ command cargo --version
cargo 1.60.0
++ command cargo check --release --all-targets
error: no matching package named `foobar` found
location searched: ssh://git@gitlab.example.com:8080/foobar.git?branch=main#d41167ba
required by package `private_package v0.1.0 (/build/private_package)`
```

Looking at the interpolated config.toml:

config.toml
```toml
[source.nix-sources-c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0]
directory = "/nix/store/qhzml8kifsmdrwk078ldpwqcivgdnjhw-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0"
[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"
replace-with = "nix-sources-c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0"

[source.nix-sources-5a1de2fe24071df3256e38ddf4b8496f55d00d943f09e12707c9991ec66b2037]
directory = "/nix/store/qhzml8kifsmdrwk078ldpwqcivgdnjhw-vendor-cargo-deps/5a1de2fe24071df3256e38ddf4b8496f55d00d943f09e12707c9991ec66b2037"
[source."ssh://git@gitlab.example.com:8080/foobar.git?branch=main"]
replace-with = "nix-sources-5a1de2fe24071df3256e38ddf4b8496f55d00d943f09e12707c9991ec66b2037"
git = "ssh://git@gitlab.example.com:8080/foobar.git"
branch = "main"
```

which seems correct, so one more down into the directory of `source.nix-sources-5a1d...`

```
✦ ❯ ls /nix/store/qhzml8kifsmdrwk078ldpwqcivgdnjhw-vendor-cargo-deps/5a1de2fe24071df3256e38ddf4b8496f55d00d943f09e12707c9991ec66b2037
foobar-0.1.0
```

Okay? And what does that point to?

```
 ❯ ls -la /nix/store/qhzml8kifsmdrwk078ldpwqcivgdnjhw-vendor-cargo-deps/5a1de2fe24071df3256e38ddf4b8496f55d00d943f09e12707c9991ec66b2037
lrwxrwxrwx 75 root  1 Jan  1970 foobar-0.1.0 -> /nix/store/4irigj2jmlawl8j7fy51rc7lkjpbhr2a-cargo-git/foobar-0.1.0
```

Let's check out that file:

```
✦ ❯ ls /nix/store/4irigj2jmlawl8j7fy51rc7lkjpbhr2a-cargo-git/foobar-0.1.0
"/nix/store/4irigj2jmlawl8j7fy51rc7lkjpbhr2a-cargo-git/foobar-0.1.0": No such file or directory (os error 2)
```

I am not sure how why this happens? In the nix repl I executed the following command: 

```nix
builtins.fetchGit { url = "ssh://git@gitlab.example.com:8080/foobar.git"; ref = "main"; }
{ lastModified = 1685439111; lastModifiedDate = "20230530093151"; narHash = "sha256-UO2IWFOFL8zw23RVmT+f24RX9MQ6yuy8oNGSoappMww="; outPath = "/nix/store/cp4xyzvb9ahy9i6vqnx6qas3li5qd8fl-source"; rev = "d41167ba97b9a34714795cd158f59efda2a6d70f"; revCount = 1614; shortRev = "d41167b"; submodules = false; }
```
Here the outPath contains the full source of the git repo, so in theory, it should have access? 

AFAIK does `builtins.fetchGit` use the ssh credentials of the invoking user. And I do have the rights to that gitlab.

I don't know what went wrong here. 

NOTE: I changed all occurences of the names and URLs, but kept the hashes. If there are any discrepancies, they are probably because I didn't replace them equally.
